name: passingDatatoanother
on:  
   workflow_dispatch:
jobs:
    read-metadata:
        runs-on: ubuntu-24.04
        steps:
            - name: Reading Meta Data
              run : echo $ {{github.repository}}
         
