name: passing Data to another

on:  
   push:

jobs:
    read-metadata:
        runs-on: ubuntu-24.04

        steps:
            - name: Reading Meta Data
              run: echo "${{toJson(github) }}"
         
