name: passing Data to another

on:  
   push:

jobs:
    read-metadata:
        runs-on: ubuntu-24.04

        steps:
            - name: Reading Meta Data
              run: echo "${{toJson(github) }}"

    settingvaluetovariable:
        runs-on: ubuntu-24.04

        outputs: 
            variable: ${{steps.assign-value.outputs.value1}}

        steps:
            - name: assign value to variable 
              id: assign-value

              run: |
                echo "value1= apple" >> "$GITHUB_OUTPUT"
                echo "value2= mango" >> "$GITHUB_ENV"
                # passingvalues between steps or jobs using outputs


            - name: "Checking the value of value1 and value2" 

              run: |
                  echo "value passed from output: ${{steps.assign-value.outputs.value1}}"
                  echo "value passed from env: $value2"


    Checkingthevalueofvalue1andvalue2:
        runs-on: ubuntu-24.04  
        needs:  settingvaluetovariable

        steps:
            - name: Checking the value of value1 and value2
              run: |
                echo "value passed from output: ${{needs.settingvaluetovariable.outputs.variable}}"
                echo "value passed from env: $value2" 
                


               



